# See config.example.yml for documentation.
object_base: orig/SVCE
object: sys/main.dol
map: orig/SVCE/sys/UnityWii.map
hash: 7f701748b9108aa9f41d7ed8b2774f86ab84d5b0
symbols: config/SVCE/symbols.txt
splits: config/SVCE/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11
